app:
  sut-config:
    base-uri: google.com/
    username: none
    password: none
    pageload-timeout: 60
  driver-config:
    type: web
    browser: chrome
    implicit-wait: 30
    hidden: false
    maximize: true