sutConfig:
  baseUri: google.com/
  username: none
  password: none
  databaseConnectionString: none
  databaseUserName: none
  databasePassword: none
driverConfig:
  driversFolderName: drivers
  type: web
  browser: firefox
  implicitWait: 30
  pageloadTimeout: 60
  drivercommandTimeout: 60
  hidden: false
  maximize: true