emailConfig:
  emailUser: none
  emailPass: none
  host: none
  sendTo: none
  subject: none
  attachedReport: true
reportConfig:
  reportFolder: TestReportMain
  convertToPdf: true
sutConfig:
  baseUri: google.com/
  accounts:
     - user1: user1
     - user2: user2
     - user3: user3
driverConfig:
  driversFolderName: drivers
  driverType: web
  implicitWait: 5
  pageloadTimeout: 60
  drivercommandTimeout: 60
  hidden: false
  maximize: false
dataSourceConfig:
  databaseDriver: com.mysql.cj.jdbc.Driver
  databaseConnectionString:  none
  databaseUserName: none
  databasePassword: none
  testDataFolder: TestData