sutConfig:
  baseUri: google2.com/
  username: none
  password: none  
driverConfig:
  driversFolderName: drivers
  type: web
  browser: firefox
  implicitWait: 30
  pageloadTimeout: 60
  drivercommandTimeout: 60
  hidden: false
  maximize: false
databaseConfig:
  databaseDriver: none
  databaseConnectionString: none
  databaseUserName: none
  databasePassword: none